var path = './resources/js';
var fs = require("fs");

fs.watch(path, function() {
    if (location)
    location.reload();
});


function getHero(id) {
    if (!Heroes[id]) {throw "No hero with this ID: " + id;}
    return Heroes[id].localized_name;
}

function getItem(id) {
    if (!Items[id]) {return "Unknown item: " + id;}
    return Items[id];
}

var Heroes = {
    1: {name: "npc_dota_hero_antimage", id: 1, localized_name: "Anti-Mage"},
    2: {name: "npc_dota_hero_axe", id: 2, localized_name: "Axe"},
    3: {name: "npc_dota_hero_bane", id: 3, localized_name: "Bane"},
    4: {name: "npc_dota_hero_bloodseeker", id: 4, localized_name: "Bloodseeker"},
    5: {name: "npc_dota_hero_crystal_maiden", id: 5, localized_name: "Crystal Maiden"},
    6: {name: "npc_dota_hero_drow_ranger", id: 6, localized_name: "Drow Ranger"},
    7: {name: "npc_dota_hero_earthshaker", id: 7, localized_name: "Earthshaker"},
    8: {name: "npc_dota_hero_juggernaut", id: 8, localized_name: "Juggernaut"},
    9: {name: "npc_dota_hero_mirana", id: 9, localized_name: "Mirana"},
    10: {name: "npc_dota_hero_morphling", id: 10, localized_name: "Morphling"},
    11: {name: "npc_dota_hero_nevermore", id: 11, localized_name: "Shadow Fiend"},
    12: {name: "npc_dota_hero_phantom_lancer", id: 12, localized_name: "Phantom Lancer"},
    13: {name: "npc_dota_hero_puck", id: 13, localized_name: "Puck"},
    14: {name: "npc_dota_hero_pudge", id: 14, localized_name: "Pudge"},
    15: {name: "npc_dota_hero_razor", id: 15, localized_name: "Razor"},
    16: {name: "npc_dota_hero_sand_king", id: 16, localized_name: "Sand King"},
    17: {name: "npc_dota_hero_storm_spirit", id: 17, localized_name: "Storm Spirit"},
    18: {name: "npc_dota_hero_sven", id: 18, localized_name: "Sven"},
    19: {name: "npc_dota_hero_tiny", id: 19, localized_name: "Tiny"},
    20: {name: "npc_dota_hero_vengefulspirit", id: 20, localized_name: "Vengeful Spirit"},
    21: {name: "npc_dota_hero_windrunner", id: 21, localized_name: "Windranger"},
    22: {name: "npc_dota_hero_zuus", id: 22, localized_name: "Zeus"},
    23: {name: "npc_dota_hero_kunkka", id: 23, localized_name: "Kunkka"},
    25: {name: "npc_dota_hero_lina", id: 25, localized_name: "Lina"},
    26: {name: "npc_dota_hero_lion", id: 26, localized_name: "Lion"},
    27: {name: "npc_dota_hero_shadow_shaman", id: 27, localized_name: "Shadow Shaman"},
    28: {name: "npc_dota_hero_slardar", id: 28, localized_name: "Slardar"},
    29: {name: "npc_dota_hero_tidehunter", id: 29, localized_name: "Tidehunter"},
    30: {name: "npc_dota_hero_witch_doctor", id: 30, localized_name: "Witch Doctor"},
    31: {name: "npc_dota_hero_lich", id: 31, localized_name: "Lich"},
    32: {name: "npc_dota_hero_riki", id: 32, localized_name: "Riki"},
    33: {name: "npc_dota_hero_enigma", id: 33, localized_name: "Enigma"},
    34: {name: "npc_dota_hero_tinker", id: 34, localized_name: "Tinker"},
    35: {name: "npc_dota_hero_sniper", id: 35, localized_name: "Sniper"},
    36: {name: "npc_dota_hero_necrolyte", id: 36, localized_name: "Necrophos"},
    37: {name: "npc_dota_hero_warlock", id: 37, localized_name: "Warlock"},
    38: {name: "npc_dota_hero_beastmaster", id: 38, localized_name: "Beastmaster"},
    39: {name: "npc_dota_hero_queenofpain", id: 39, localized_name: "Queen of Pain"},
    40: {name: "npc_dota_hero_venomancer", id: 40, localized_name: "Venomancer"},
    41: {name: "npc_dota_hero_faceless_void", id: 41, localized_name: "Faceless Void"},
    42: {name: "npc_dota_hero_skeleton_king", id: 42, localized_name: "Wraith King"},
    43: {name: "npc_dota_hero_death_prophet", id: 43, localized_name: "Death Prophet"},
    44: {name: "npc_dota_hero_phantom_assassin", id: 44, localized_name: "Phantom Assassin"},
    45: {name: "npc_dota_hero_pugna", id: 45, localized_name: "Pugna"},
    46: {name: "npc_dota_hero_templar_assassin", id: 46, localized_name: "Templar Assassin"},
    47: {name: "npc_dota_hero_viper", id: 47, localized_name: "Viper"},
    48: {name: "npc_dota_hero_luna", id: 48, localized_name: "Luna"},
    49: {name: "npc_dota_hero_dragon_knight", id: 49, localized_name: "Dragon Knight"},
    50: {name: "npc_dota_hero_dazzle", id: 50, localized_name: "Dazzle"},
    51: {name: "npc_dota_hero_rattletrap", id: 51, localized_name: "Clockwerk"},
    52: {name: "npc_dota_hero_leshrac", id: 52, localized_name: "Leshrac"},
    53: {name: "npc_dota_hero_furion", id: 53, localized_name: "Nature's Prophet"},
    54: {name: "npc_dota_hero_life_stealer", id: 54, localized_name: "Lifestealer"},
    55: {name: "npc_dota_hero_dark_seer", id: 55, localized_name: "Dark Seer"},
    56: {name: "npc_dota_hero_clinkz", id: 56, localized_name: "Clinkz"},
    57: {name: "npc_dota_hero_omniknight", id: 57, localized_name: "Omniknight"},
    58: {name: "npc_dota_hero_enchantress", id: 58, localized_name: "Enchantress"},
    59: {name: "npc_dota_hero_huskar", id: 59, localized_name: "Huskar"},
    60: {name: "npc_dota_hero_night_stalker", id: 60, localized_name: "Night Stalker"},
    61: {name: "npc_dota_hero_broodmother", id: 61, localized_name: "Broodmother"},
    62: {name: "npc_dota_hero_bounty_hunter", id: 62, localized_name: "Bounty Hunter"},
    63: {name: "npc_dota_hero_weaver", id: 63, localized_name: "Weaver"},
    64: {name: "npc_dota_hero_jakiro", id: 64, localized_name: "Jakiro"},
    65: {name: "npc_dota_hero_batrider", id: 65, localized_name: "Batrider"},
    66: {name: "npc_dota_hero_chen", id: 66, localized_name: "Chen"},
    67: {name: "npc_dota_hero_spectre", id: 67, localized_name: "Spectre"},
    68: {name: "npc_dota_hero_ancient_apparition", id: 68, localized_name: "Ancient Apparition"},
    69: {name: "npc_dota_hero_doom_bringer", id: 69, localized_name: "Doom"},
    70: {name: "npc_dota_hero_ursa", id: 70, localized_name: "Ursa"},
    71: {name: "npc_dota_hero_spirit_breaker", id: 71, localized_name: "Spirit Breaker"},
    72: {name: "npc_dota_hero_gyrocopter", id: 72, localized_name: "Gyrocopter"},
    73: {name: "npc_dota_hero_alchemist", id: 73, localized_name: "Alchemist"},
    74: {name: "npc_dota_hero_invoker", id: 74, localized_name: "Invoker"},
    75: {name: "npc_dota_hero_silencer", id: 75, localized_name: "Silencer"},
    76: {name: "npc_dota_hero_obsidian_destroyer", id: 76, localized_name: "Outworld Devourer"},
    77: {name: "npc_dota_hero_lycan", id: 77, localized_name: "Lycan"},
    78: {name: "npc_dota_hero_brewmaster", id: 78, localized_name: "Brewmaster"},
    79: {name: "npc_dota_hero_shadow_demon", id: 79, localized_name: "Shadow Demon"},
    80: {name: "npc_dota_hero_lone_druid", id: 80, localized_name: "Lone Druid"},
    81: {name: "npc_dota_hero_chaos_knight", id: 81, localized_name: "Chaos Knight"},
    82: {name: "npc_dota_hero_meepo", id: 82, localized_name: "Meepo"},
    83: {name: "npc_dota_hero_treant", id: 83, localized_name: "Treant Protector"},
    84: {name: "npc_dota_hero_ogre_magi", id: 84, localized_name: "Ogre Magi"},
    85: {name: "npc_dota_hero_undying", id: 85, localized_name: "Undying"},
    86: {name: "npc_dota_hero_rubick", id: 86, localized_name: "Rubick"},
    87: {name: "npc_dota_hero_disruptor", id: 87, localized_name: "Disruptor"},
    88: {name: "npc_dota_hero_nyx_assassin", id: 88, localized_name: "Nyx Assassin"},
    89: {name: "npc_dota_hero_naga_siren", id: 89, localized_name: "Naga Siren"},
    90: {name: "npc_dota_hero_keeper_of_the_light", id: 90, localized_name: "Keeper of the Light"},
    91: {name: "npc_dota_hero_wisp", id: 91, localized_name: "Io"},
    92: {name: "npc_dota_hero_visage", id: 92, localized_name: "Visage"},
    93: {name: "npc_dota_hero_slark", id: 93, localized_name: "Slark"},
    94: {name: "npc_dota_hero_medusa", id: 94, localized_name: "Medusa"},
    95: {name: "npc_dota_hero_troll_warlord", id: 95, localized_name: "Troll Warlord"},
    96: {name: "npc_dota_hero_centaur", id: 96, localized_name: "Centaur Warrunner"},
    97: {name: "npc_dota_hero_magnataur", id: 97, localized_name: "Magnus"},
    98: {name: "npc_dota_hero_shredder", id: 98, localized_name: "Timbersaw"},
    99: {name: "npc_dota_hero_bristleback", id: 99, localized_name: "Bristleback"},
    100: {name: "npc_dota_hero_tusk", id: 100, localized_name: "Tusk"},
    101: {name: "npc_dota_hero_skywrath_mage", id: 101, localized_name: "Skywrath Mage"},
    102: {name: "npc_dota_hero_abaddon", id: 102, localized_name: "Abaddon"},
    103: {name: "npc_dota_hero_elder_titan", id: 103, localized_name: "Elder Titan"},
    104: {name: "npc_dota_hero_legion_commander", id: 104, localized_name: "Legion Commander"},
    105: {name: "npc_dota_hero_techies", id: 105, localized_name: "Techies"},
    106: {name: "npc_dota_hero_ember_spirit", id: 106, localized_name: "Ember Spirit"},
    107: {name: "npc_dota_hero_earth_spirit", id: 107, localized_name: "Earth Spirit"},
    109: {name: "npc_dota_hero_terrorblade", id: 109, localized_name: "Terrorblade"},
    110: {name: "npc_dota_hero_phoenix", id: 110, localized_name: "Phoenix"},
    111: {name: "npc_dota_hero_oracle", id: 111, localized_name: "Oracle"},
    112: {name: "winter_wyvern", id: 112, localized_name: "Winter Wyvern"},
    113: {name: "arc_warden", id: 113, localized_name: "Arc Warden"}
};

var heroes = [];

(function() {
    var ks = Object.keys(Heroes);
    ks.forEach(function(i, x) {
        heroes[x] = Heroes[i];
    });
})();


var Items = {
    0: "empty",
    1: "blink",
    2: "blades_of_attack",
    3: "broadsword",
    4: "chainmail",
    5: "claymore",
    6: "helm_of_iron_will",
    7: "javelin",
    8: "mithril_hammer",
    9: "platemail",
    10: "quarterstaff",
    11: "quelling_blade",
    12: "ring_of_protection",
    13: "gauntlets",
    14: "slippers",
    15: "mantle",
    16: "branches",
    17: "belt_of_strength",
    18: "boots_of_elves",
    19: "robe",
    20: "circlet",
    21: "ogre_axe",
    22: "blade_of_alacrity",
    23: "staff_of_wizardry",
    24: "ultimate_orb",
    25: "gloves",
    26: "lifesteal",
    27: "ring_of_regen",
    28: "sobi_mask",
    29: "boots",
    30: "gem",
    31: "cloak",
    32: "talisman_of_evasion",
    33: "cheese",
    34: "magic_stick",
    35: "recipe_magic_wand",
    36: "magic_wand",
    37: "ghost",
    38: "clarity",
    39: "flask",
    40: "dust",
    41: "bottle",
    42: "ward_observer",
    43: "ward_sentry",
    44: "tango",
    45: "courier",
    46: "tpscroll",
    47: "recipe_travel_boots",
    48: "travel_boots",
    49: "recipe_phase_boots",
    50: "phase_boots",
    51: "demon_edge",
    52: "eagle",
    53: "reaver",
    54: "relic",
    55: "hyperstone",
    56: "ring_of_health",
    57: "void_stone",
    58: "mystic_staff",
    59: "energy_booster",
    60: "point_booster",
    61: "vitality_booster",
    62: "recipe_power_treads",
    63: "power_treads",
    64: "recipe_hand_of_midas",
    65: "hand_of_midas",
    66: "recipe_oblivion_staff",
    67: "oblivion_staff",
    68: "recipe_pers",
    69: "pers",
    70: "recipe_poor_mans_shield",
    71: "poor_mans_shield",
    72: "recipe_bracer",
    73: "bracer",
    74: "recipe_wraith_band",
    75: "wraith_band",
    76: "recipe_null_talisman",
    77: "null_talisman",
    78: "recipe_mekansm",
    79: "mekansm",
    80: "recipe_vladmir",
    81: "vladmir",
    84: "flying_courier",
    85: "recipe_buckler",
    86: "buckler",
    87: "recipe_ring_of_basilius",
    88: "ring_of_basilius",
    89: "recipe_pipe",
    90: "pipe",
    91: "recipe_urn_of_shadows",
    92: "urn_of_shadows",
    93: "recipe_headdress",
    94: "headdress",
    95: "recipe_sheepstick",
    96: "sheepstick",
    97: "recipe_orchid",
    98: "orchid",
    99: "recipe_cyclone",
    100: "cyclone",
    101: "recipe_force_staff",
    102: "force_staff",
    103: "recipe_dagon",
    104: "dagon",
    105: "recipe_necronomicon",
    106: "necronomicon",
    107: "recipe_ultimate_scepter",
    108: "ultimate_scepter",
    109: "recipe_refresher",
    110: "refresher",
    111: "recipe_assault",
    112: "assault",
    113: "recipe_heart",
    114: "heart",
    115: "recipe_black_king_bar",
    116: "black_king_bar",
    117: "aegis",
    118: "recipe_shivas_guard",
    119: "shivas_guard",
    120: "recipe_bloodstone",
    121: "bloodstone",
    122: "recipe_sphere",
    123: "sphere",
    124: "recipe_vanguard",
    125: "vanguard",
    126: "recipe_blade_mail",
    127: "blade_mail",
    128: "recipe_soul_booster",
    129: "soul_booster",
    130: "recipe_hood_of_defiance",
    131: "hood_of_defiance",
    132: "recipe_rapier",
    133: "rapier",
    134: "recipe_monkey_king_bar",
    135: "monkey_king_bar",
    136: "recipe_radiance",
    137: "radiance",
    138: "recipe_butterfly",
    139: "butterfly",
    140: "recipe_greater_crit",
    141: "greater_crit",
    142: "recipe_basher",
    143: "basher",
    144: "recipe_bfury",
    145: "bfury",
    146: "recipe_manta",
    147: "manta",
    148: "recipe_lesser_crit",
    149: "lesser_crit",
    150: "recipe_armlet",
    151: "armlet",
    152: "invis_sword",
    153: "recipe_sange_and_yasha",
    154: "sange_and_yasha",
    155: "recipe_satanic",
    156: "satanic",
    157: "recipe_mjollnir",
    158: "mjollnir",
    159: "recipe_skadi",
    160: "skadi",
    161: "recipe_sange",
    162: "sange",
    163: "recipe_helm_of_the_dominator",
    164: "helm_of_the_dominator",
    165: "recipe_maelstrom",
    166: "maelstrom",
    167: "recipe_desolator",
    168: "desolator",
    169: "recipe_yasha",
    170: "yasha",
    171: "recipe_mask_of_madness",
    172: "mask_of_madness",
    173: "recipe_diffusal_blade",
    174: "diffusal_blade",
    175: "recipe_ethereal_blade",
    176: "ethereal_blade",
    177: "recipe_soul_ring",
    178: "soul_ring",
    179: "recipe_arcane_boots",
    180: "arcane_boots",
    181: "orb_of_venom",
    182: "stout_shield",
    183: "recipe_invis_sword",
    184: "recipe_ancient_janggo",
    185: "ancient_janggo",
    186: "recipe_medallion_of_courage",
    187: "medallion_of_courage",
    188: "smoke_of_deceit",
    189: "recipe_veil_of_discord",
    190: "veil_of_discord",
    191: "recipe_necronomicon_2",
    192: "recipe_necronomicon_3",
    193: "necronomicon_2",
    194: "necronomicon_3",
    195: "recipe_diffusal_blade_2",
    196: "diffusal_blade_2",
    197: "recipe_dagon_2",
    198: "recipe_dagon_3",
    199: "recipe_dagon_4",
    200: "recipe_dagon_5",
    201: "dagon_2",
    202: "dagon_3",
    203: "dagon_4",
    204: "dagon_5",
    205: "recipe_rod_of_atos",
    206: "rod_of_atos",
    207: "recipe_abyssal_blade",
    208: "abyssal_blade",
    209: "recipe_heavens_halberd",
    210: "heavens_halberd",
    211: "recipe_ring_of_aquila",
    212: "ring_of_aquila",
    213: "recipe_tranquil_boots",
    214: "tranquil_boots",
    215: "shadow_amulet",
    216: "enchanted_mango",
    218: "ward_dispenser",
    220: "travel_boots_2",
    226: "lotus_orb",
    229: "solar_crest",
    231: "guardian_greaves",
    232: "aether_lens",
    233: "recipe_aether_lens",
    234: "recipe_dragon_lance",
    235: "octarine_core",
    236: "dragon_lance",
    237: "faerie_fire",
    238: "recipe_iron_talon",
    239: "iron_talon",
    240: "blight_stone",
    241: "tango_single",
    242: "crimson_guard",
    244: "wind_lace",
    245: "recipe_bloodthorn",
    247: "moon_shard",
    249: "silver_edge",
    250: "bloodthorn",
    251: "recipe_echo_sabre",
    252: "echo_sabre",
    254: "glimmer_cape",
    257: "tome_of_knowledge",
    262: "recipe_hurricane_pike",
    263: "hurricane_pike",
    265: "infused_raindrop",
    1000: "halloween_candy_corn",
    1001: "mystery_hook",
    1002: "mystery_arrow",
    1003: "mystery_missile",
    1004: "mystery_toss",
    1005: "mystery_vacuum",
    1006: "halloween_rapier",
    1007: "greevil_whistle",
    1008: "greevil_whistle_toggle",
    1009: "present",
    1010: "winter_stocking",
    1011: "winter_skates",
    1012: "winter_cake",
    1013: "winter_cookie",
    1014: "winter_coco",
    1015: "winter_ham",
    1016: "winter_kringle",
    1017: "winter_mushroom",
    1018: "winter_greevil_treat",
    1019: "winter_greevil_garbage",
    1020: "winter_greevil_chewy"
};

var listOptions = [
    "assists",
    "deaths",
    "denies",
    "gold",
    "gold_per_min",
    "gold_spent",
    "hero_damage",
    "hero_healing",
    "hero_id",
    "kills",
    "last_hits",
    "level",
    "tower_damage",
    "xp_per_min"];
